// Contour lines, generated by marching-squares over a scalar field in normalized
// 0..1 map space. Defaults to the altitude field the elevation profile slices
// through (utils/metaphor.altitudeAt), so the contours aren't decoration — the
// "mountains" are exactly where the high-energy tracks pile up. Pass a different
// `field` to trace any other dimension (style density, groove intensity …).
import { altitudeAt } from './metaphor.js'
import { lerp } from './rng.js'

// Sample the field on a res×res grid, then trace iso-lines at nLevels heights.
export function generateContours({ res = 72, nLevels = 9, pad = 0.04, field: fieldFn = altitudeAt } = {}) {
  const g = res + 1
  const field = new Float32Array(g * g)
  let min = Infinity
  let max = -Infinity
  const at = (i, j) => {
    const x = lerp(-pad, 1 + pad, i / res)
    const y = lerp(-pad, 1 + pad, j / res)
    return fieldFn(x, y)
  }
  for (let j = 0; j <= res; j++) {
    for (let i = 0; i <= res; i++) {
      const v = at(i, j)
      field[j * g + i] = v
      if (v < min) min = v
      if (v > max) max = v
    }
  }

  const toMap = (i, j) => [
    lerp(-pad, 1 + pad, i / res),
    lerp(-pad, 1 + pad, j / res),
  ]

  const levels = []
  for (let l = 1; l <= nLevels; l++) {
    const iso = lerp(min, max, l / (nLevels + 1))
    const segments = []
    for (let j = 0; j < res; j++) {
      for (let i = 0; i < res; i++) {
        const tl = field[j * g + i]
        const tr = field[j * g + i + 1]
        const br = field[(j + 1) * g + i + 1]
        const bl = field[(j + 1) * g + i]
        let idx = 0
        if (tl > iso) idx |= 8
        if (tr > iso) idx |= 4
        if (br > iso) idx |= 2
        if (bl > iso) idx |= 1
        if (idx === 0 || idx === 15) continue

        // Interpolated crossings on each cell edge.
        const [x0, y0] = toMap(i, j)
        const [x1, y1] = toMap(i + 1, j + 1)
        const top = () => [lerp(x0, x1, (iso - tl) / (tr - tl)), y0]
        const bottom = () => [lerp(x0, x1, (iso - bl) / (br - bl)), y1]
        const left = () => [x0, lerp(y0, y1, (iso - tl) / (bl - tl))]
        const right = () => [x1, lerp(y0, y1, (iso - tr) / (br - tr))]

        const push = (p, q) => segments.push([p[0], p[1], q[0], q[1]])
        switch (idx) {
          case 1: push(left(), bottom()); break
          case 2: push(bottom(), right()); break
          case 3: push(left(), right()); break
          case 4: push(top(), right()); break
          case 5: push(left(), top()); push(bottom(), right()); break
          case 6: push(top(), bottom()); break
          case 7: push(left(), top()); break
          case 8: push(left(), top()); break
          case 9: push(top(), bottom()); break
          case 10: push(top(), right()); push(left(), bottom()); break
          case 11: push(top(), right()); break
          case 12: push(left(), right()); break
          case 13: push(bottom(), right()); break
          case 14: push(left(), bottom()); break
          default: break
        }
      }
    }
    levels.push({ value: iso, rank: l / (nLevels + 1), segments })
  }
  return { levels, min, max }
}

// Turn a level's loose segments into SVG path data (each segment is its own move,
// which is fine for hachure-style contour strokes).
export function segmentsToPath(segments, scaleX, scaleY) {
  let d = ''
  for (const [x1, y1, x2, y2] of segments) {
    d += `M${(x1 * scaleX).toFixed(1)} ${(y1 * scaleY).toFixed(1)}L${(x2 * scaleX).toFixed(1)} ${(y2 * scaleY).toFixed(1)}`
  }
  return d
}
